elera:
  cache.refresh: true
  clear:
    db: false
    transactions: false
  loader:
    data-path: /home/linuxbox/tgcs/projects/sandbox/src/demo-docker-shared-vol/datasets/src/main/resources
    datasets: [ base-eu, demo, qa ]
  mongodb:
    seed:
      include: ''
      exclude: ''
  sample:
    order: true

logging:
  level:
    root: ERROR
    app: DEBUG
    org.springframework.integration:
          handler.LoggingHandler: INFO
          channel.DirectChannel: INFO

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/poc
